;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-indent-line-or-region
	indent-for-tab-command
	nxml-electric-slash
	tab-to-tab-stop
	))

(setq mc/cmds-to-run-once
      '(
	eval-print-last-sexp
	expand-or-mark-next-like-this
	))
